apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: config-secrets
        secret:
          secretName: authbasic
          items:
          - key: info
            path: info
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/nginx"
        - name: config-secrets
          mountPath: "/etc/nginx/conf.d"
---
kind: Service
apiVersion: v1
metadata:
  name: sf-webserver
spec:
  selector:
    app: myapp-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

