all:
  hosts:
    node1:
      ansible_host: 192.168.80.1
      ip: 192.168.80.1
      access_ip: 192.168.80.1
    node2:
      ansible_host: 192.168.80.2
      ip: 192.168.80.2
      access_ip: 192.168.80.2
    node3:
      ansible_host: 192.168.80.3
      ip: 192.168.80.3
      access_ip: 192.168.80.3
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
