version: "3.9"

services:
  php: 
    build: .
    environment:
      TZ: "Asia/Tashkent"
    volumes: 
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www/index.php:/var/www/index.php
    healthcheck:
      test: ["CMD", "curl -sS http://nginx | grep -c works > /dev/null "]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web_lan

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
       - "80:80"
    environment:
      TZ: "Asia/Tashkent"
    networks:
      - web_lan
    volumes: 
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www/index.php:/var/www/index.php
    ports: 
      - 80:80
    command:  nginx-debug -g 'daemon off;'
    links:
      - php
        
networks:
  web_lan:

