# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  # Указываем базовый образ ubuntu 18.0.4
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.10"

  # Копируем файл из локальной системы в гостевую
  config.vm.provision "file", source: "test_file", destination: "/tmp/test_file"
  
  # создаем виртуалку
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "2048"
	 vb.cpus = "2"
  end
  # Указываем timezone чтоб не было проблем с apt
	if Vagrant.has_plugin?("vagrant-timezone")
		config.timezone.value = "Asia/Tashkent"
   end
  # устанавливаем все необходимое
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-dev python3-pip libpq-dev
	pip3 install psycopg2 
	pip3 install django
  SHELL
 
end
