[app]
vm2 ansible_host=10.50.50.100
vm3 ansible_host=10.50.50.101

[database]
vm1 ansible_host=10.50.50.98

[web]
vm1 ansible_host=10.50.50.98

[all:vars]
postgresql_version="14"
postgresql_data_dir="/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_bin_path="/usr/lib/postgresql/{{ postgresql_version }}/bin"